### PR TITLE
Correct spelling of `containername` argument.

### LINKED ISSUE #1570: Rename `containername` mega-linter-runner argument to `container-name`
**Describe the bug**

It seems odd to spell the argument `containername` when the name of the package itself is hyphenated, and `containername` will get flagged as a CSpell error in downstream projects that use MegaLinter (e.g., when committing a script that runs MegaLinter to their `package.json` or `.pre-commit-config.yaml`). I did the code review in which this feature was added, so apologies for not considering this sooner.

**To Reproduce**

1. Read [mega-linter-runner usage docs](https://megalinter.github.io/5.16.1/mega-linter-runner/#usage).

**Expected behavior**

I expected the argument to have a correctly spelled name.

**Additional context**

I considered adding "containername" to CSpell in streetsidesoftware/cspell-dicts#1207, and the maintainer understandably discouraged adding a misspelled word.

### PR DESCRIPTION
**Pull request by Kurt-von-Laven**
Fixes #1570.

## Proposed Changes

1. Spell the new mega-linter-runner argument `container-name` for consistency with the package name, mega-linter-runner, and to spare users from needing to add `containername` as a CSpell exception.
2. Remove the CSpell exception for `containername` to prove that no references were missed and as a regression test.
3. Make minor formatting improvements to runner.js for consistency with #1563 based on my code review feedback on #1561.

### Author/Contributor
- [x] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [x] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by nvuillam** [comment]
## [MegaLinter](https://megalinter.github.io) status: :warning: [**WARNING**](https://github.com/megalinter/megalinter/actions/runs/2574326616)

|   Descriptor   |                                                Linter                                                |Files|Fixed|                                  Errors                                  |Elapsed time|
|----------------|------------------------------------------------------------------------------------------------------|-----|----:|--------------------------------------------------------------------------|------------|
|✅ BASH         |[bash-exec](https://megalinter.github.io/descriptors/bash_bash_exec)                                  |    6|     |                                                                         0|0.02s       |
|✅ BASH         |[shellcheck](https://megalinter.github.io/descriptors/bash_shellcheck)                                |    6|     |                                                                         0|0.23s       |
|✅ BASH         |[shfmt](https://megalinter.github.io/descriptors/bash_shfmt)                                          |    6|    0|                                                                         0|0.05s       |
|✅ COPYPASTE    |[jscpd](https://megalinter.github.io/descriptors/copypaste_jscpd)                                     |yes  |     |no                                                                        |1.77s       |
|✅ CREDENTIALS  |[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no                                                                        |3.56s       |
|✅ DOCKERFILE   |[dockerfilelint](https://megalinter.github.io/descriptors/dockerfile_dockerfilelint)                  |    1|     |                                                                         0|0.23s       |
|✅ DOCKERFILE   |[hadolint](https://megalinter.github.io/descriptors/dockerfile_hadolint)                              |    1|     |                                                                         0|0.7s        |
|✅ GIT          |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no                                                                        |0.03s       |
|✅ JSON         |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |   21|    0|                                                                         0|1.8s        |
|✅ JSON         |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |   19|     |                                                                         0|4.56s       |
|✅ JSON         |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |   21|     |                                                                         0|17.65s      |
|✅ MARKDOWN     |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |  255|    2|                                                                         0|4.41s       |
|✅ MARKDOWN     |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |  255|     |                                                                         0|4.42s       |
|✅ MARKDOWN     |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|  255|    2|                                                                         0|4.49s       |
|✅ OPENAPI      |[spectral](https://megalinter.github.io/descriptors/openapi_spectral)                                 |    1|     |                                                                         0|0.95s       |
|:warning: PYTHON|[bandit](https://megalinter.github.io/descriptors/python_bandit)                                      |  150|     |[**65**](https://github.com/megalinter/megalinter/actions/runs/2574326616)|1.8s        |
|✅ PYTHON       |[black](https://megalinter.github.io/descriptors/python_black)                                        |  150|    0|                                                                         0|2.83s       |
|✅ PYTHON       |[flake8](https://megalinter.github.io/descriptors/python_flake8)                                      |  150|     |                                                                         0|2.31s       |
|✅ PYTHON       |[isort](https://megalinter.github.io/descriptors/python_isort)                                        |  150|    0|                                                                         0|0.31s       |
|✅ PYTHON       |[mypy](https://megalinter.github.io/descriptors/python_mypy)                                          |  150|     |                                                                         0|96.07s      |
|✅ PYTHON       |[pylint](https://megalinter.github.io/descriptors/python_pylint)                                      |  150|     |                                                                         0|13.68s      |
|✅ SPELL        |[cspell](https://megalinter.github.io/descriptors/spell_cspell)                                       |  534|     |                                                                         0|13.77s      |
|✅ SPELL        |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |  378|    2|                                                                         0|0.29s       |
|✅ XML          |[xmllint](https://megalinter.github.io/descriptors/xml_xmllint)                                       |    2|     |                                                                         0|0.0s        |
|✅ YAML         |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |   77|    0|                                                                         0|2.31s       |
|✅ YAML         |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |   20|     |                                                                         0|30.62s      |
|✅ YAML         |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |   78|     |                                                                         0|1.26s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/megalinter/megalinter/actions/runs/2574326616)

You could have the same capabilities but better runtime performances if you use a MegaLinter flavor:
- [**megalinter/megalinter/flavors/python@v5**](https://megalinter.github.io/flavors/python/) (49 linters)

**Comment by nvuillam** [comment]
@Kurt-von-Laven this would be a breaking change for people using containername argument :/

**Comment by Kurt-von-Laven** [comment]
Is it worth doing in v7? I think the current unconventional spelling may cause some frustration for users who aren't yet using it. I understandably got push back from the CSpell maintainer when I proposed adding `containername` to the software-terms dictionary since he couldn't find much evidence of other projects that use this spelling.

**Comment by nvuillam** [comment]
Let's have a stable v6 before thinking about v7 haha ^^
But we can write that somwhere for someday ^^

File: mega-linter-runner/lib/runner.js [hunk 1]
```diff
@@ -124,8 +124,8 @@ ERROR: Docker engine has not been found on your system.
     if (options["remove-container"]) {
```
Comment (dmitri-trofimov) [inline mega-linter-runner/lib/runner.js:124]: This doesn't really work. The `optionater` converts hyphen-separated options to _camelCase_ property instead of _kebab-case_. I know I was the one to introduce this bug, but since you already have the PR, I kindly ask you to apply these changes:
```suggestion
    if (options.removeContainer) {
```

File: mega-linter-runner/lib/runner.js [hunk 2]
```diff
@@ -124,8 +124,8 @@ ERROR: Docker engine has not been found on your system.
...
       commandArgs.push("--rm");
     }
-    if (options.containername) {
-      commandArgs.push(...["--name", options.containername]);
+    if (options["container-name"]) {
```
Comment (dmitri-trofimov) [inline mega-linter-runner/lib/runner.js:127]:
```suggestion
    if (options.containerName) {
```

File: mega-linter-runner/lib/runner.js [hunk 3]
```diff
@@ -124,8 +124,8 @@ ERROR: Docker engine has not been found on your system.
...
+      commandArgs.push(...["--name", options["container-name"]]);
```
Comment (dmitri-trofimov) [inline mega-linter-runner/lib/runner.js:128]:
```suggestion
      commandArgs.push(...["--name", options.containerName]);
```

File: mega-linter-runner/lib/options.js [hunk 4]
```diff
@@ -122,7 +122,7 @@ module.exports = optionator({
       description: "Upgrade local repository MegaLinter configuration",
     },
     {
-      option: "containername",
+      option: "container-name",
```
Comment (dmitri-trofimov) [inline mega-linter-runner/lib/options.js:125]: Adding `alias: "containername"` will maintain backward compatibility:
```suggestion
      option: "container-name",
      alias: "containername",
```

File: mega-linter-runner/lib/runner.js (hunk 1 above)
Comment (Kurt-von-Laven) [reply mega-linter-runner/lib/runner.js:124]: Thank you for the catch. This must be the cause of #1917. I've opened #1928 to address this.

File: mega-linter-runner/lib/options.js (hunk 4 above)
Comment (Kurt-von-Laven) [reply mega-linter-runner/lib/options.js:125]: @nvuillam, I think this can now be merged in v6 thanks to @dmitri-trofimov's excellent suggestion.

File: mega-linter-runner/lib/runner.js (hunk 3 above)
Comment (Kurt-von-Laven) [reply mega-linter-runner/lib/runner.js]: Incorporated!

File: mega-linter-runner/lib/runner.js (hunk 2 above)
Comment (Kurt-von-Laven) [reply mega-linter-runner/lib/runner.js]: Incorporated!

**Review by nvuillam — APPROVED** [review]
great :)
